<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="20" skipped="0" tests="41" time="23.569" timestamp="2022-07-20T21:07:43.574240" hostname="hamza-VirtualBox"><testcase classname="src.assistant3.processors.__init__" name="PYLINT" time="0.002"><failure message="F:  1, 0: No module named src/assistant3/processors/__init__.py (fatal)">F:  1, 0: No module named src/assistant3/processors/__init__.py (fatal)</failure></testcase><testcase classname="src.assistant3.processors.__init__.flake-8" name="FLAKE8" time="0.597" /><testcase classname="src.assistant3.processors.__init__" name="mypy" time="4.265" /><testcase classname="src.assistant3.processors.__init__" name="mypy-status" time="0.003"><failure message="mypy exited with status 1.">mypy exited with status 1.</failure></testcase><testcase classname="src.assistant3.processors.__init__" name="YAPF" time="0.018" /><testcase classname="src.assistant3.processors.base_processor" name="PYLINT" time="0.003"><failure message="F:  1, 0: No module named src/assistant3/processors/base_processor.py (fatal)">F:  1, 0: No module named src/assistant3/processors/base_processor.py (fatal)</failure></testcase><testcase classname="src.assistant3.processors.base_processor.flake-8" name="FLAKE8" time="4.040"><failure message="/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:23:9: E265 block comment should start with '# '&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:841:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:853:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:910:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:960:1: D107 Missing docstring in __init__&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:1013:1: D101 Missing docstring in public class&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:1076:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:1086:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:1156:9: E265 block comment should start with '# '&#10;">/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:23:9: E265 block comment should start with '# '
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:841:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:853:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:910:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:960:1: D107 Missing docstring in __init__
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:1013:1: D101 Missing docstring in public class
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:1076:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:1086:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/base_processor.py:1156:9: E265 block comment should start with '# '
</failure></testcase><testcase classname="src.assistant3.processors.base_processor" name="mypy" time="0.001"><failure message="7: error: Skipping analyzing &quot;pyttsx3&quot;: module is installed, but missing library stubs or py.typed marker&#10;7: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports&#10;9: error: Cannot find implementation or library stub for module named &quot;xlsxwriter&quot;&#10;10: error: Skipping analyzing &quot;word2number&quot;: module is installed, but missing library stubs or py.typed marker&#10;198: error: Missing positional argument &quot;match&quot; in call to &quot;__init__&quot; of &quot;BasePlugin&quot;&#10;821: error: Argument 2 for &quot;super&quot; not an instance of argument 1&#10;822: error: &quot;object&quot; has no attribute &quot;queue&quot;&#10;823: error: &quot;object&quot; has no attribute &quot;min_similarity&quot;&#10;827: error: &quot;object&quot; has no attribute &quot;get_next_item&quot;&#10;831: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;834: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;835: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;838: error: &quot;object&quot; has no attribute &quot;interrupt_task&quot;&#10;846: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;847: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;848: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;849: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;850: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;864: error: &quot;OrderManager&quot; has no attribute &quot;update_db&quot;&#10;868: error: &quot;OrderManager&quot; has no attribute &quot;update_db&quot;&#10;900: error: Argument 2 for &quot;super&quot; not an instance of argument 1&#10;901: error: &quot;object&quot; has no attribute &quot;queue&quot;&#10;902: error: &quot;object&quot; has no attribute &quot;min_similarity&quot;&#10;906: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;906: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;907: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;961: error: Argument 2 for &quot;super&quot; not an instance of argument 1&#10;962: error: &quot;object&quot; has no attribute &quot;queue&quot;&#10;963: error: &quot;object&quot; has no attribute &quot;min_similarity&quot;&#10;967: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;967: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;968: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;982: error: &quot;OrderManager&quot; has no attribute &quot;get_interrupt_control&quot;&#10;988: error: &quot;OrderManager&quot; has no attribute &quot;get_interrupt_control&quot;&#10;993: error: &quot;OrderManager&quot; has no attribute &quot;set_interrupt_control&quot;&#10;1017: error: Argument 2 for &quot;super&quot; not an instance of argument 1&#10;1018: error: &quot;object&quot; has no attribute &quot;queue&quot;&#10;1019: error: &quot;object&quot; has no attribute &quot;min_similarity&quot;&#10;1023: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1024: error: &quot;object&quot; has no attribute &quot;get_next_item&quot;&#10;1025: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1026: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1027: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1029: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;1029: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1030: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;1031: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1032: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1033: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1035: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;1035: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1036: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;1040: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1043: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;1044: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;1047: error: &quot;object&quot; has no attribute &quot;interrupt_task&quot;&#10;1051: error: &quot;object&quot; has no attribute &quot;check_pick_ability&quot;&#10;1052: error: &quot;object&quot; has no attribute &quot;set_order_id&quot;&#10;1054: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1055: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;1056: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;1059: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1062: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1063: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1064: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;1065: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;1068: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1070: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1071: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1072: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;1073: error: &quot;object&quot; has no attribute &quot;engine&quot;&#10;1081: error: &quot;object&quot; has no attribute &quot;set_order_id&quot;&#10;1083: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1091: error: &quot;object&quot; has no attribute &quot;order_manager&quot;&#10;1101: error: Incompatible types in assignment (expression has type &quot;object&quot;, variable has type &quot;str&quot;)&#10;1103: error: &quot;OrderManager&quot; has no attribute &quot;get_interrupt_control&quot;&#10;1104: error: &quot;OrderManager&quot; has no attribute &quot;get_interrupt_control&quot;&#10;1107: error: &quot;OrderManager&quot; has no attribute &quot;get_interrupt_control&quot;&#10;1108: error: &quot;OrderManager&quot; has no attribute &quot;set_interrupt_control&quot;&#10;1110: error: &quot;OrderManager&quot; has no attribute &quot;get_interrupt_control&quot;&#10;1111: error: &quot;OrderManager&quot; has no attribute &quot;set_interrupt_control&quot;&#10;1113: error: &quot;OrderManager&quot; has no attribute &quot;get_interrupt_control&quot;&#10;1116: error: &quot;OrderManager&quot; has no attribute &quot;update_db&quot;&#10;1117: error: &quot;OrderManager&quot; has no attribute &quot;get_interrupt_control&quot;&#10;1122: error: &quot;OrderManager&quot; has no attribute &quot;creat_list_order&quot;&#10;1123: error: &quot;OrderManager&quot; has no attribute &quot;update_db&quot;&#10;1167: error: Argument 1 to &quot;check_order_triger&quot; of &quot;OrderManager&quot; has incompatible type &quot;object&quot;; expected &quot;str&quot;">7: error: Skipping analyzing "pyttsx3": module is installed, but missing library stubs or py.typed marker
7: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
9: error: Cannot find implementation or library stub for module named "xlsxwriter"
10: error: Skipping analyzing "word2number": module is installed, but missing library stubs or py.typed marker
198: error: Missing positional argument "match" in call to "__init__" of "BasePlugin"
821: error: Argument 2 for "super" not an instance of argument 1
822: error: "object" has no attribute "queue"
823: error: "object" has no attribute "min_similarity"
827: error: "object" has no attribute "get_next_item"
831: error: "object" has no attribute "order_manager"
834: error: "object" has no attribute "engine"
835: error: "object" has no attribute "engine"
838: error: "object" has no attribute "interrupt_task"
846: error: "object" has no attribute "order_manager"
847: error: "object" has no attribute "order_manager"
848: error: "object" has no attribute "order_manager"
849: error: "object" has no attribute "engine"
850: error: "object" has no attribute "engine"
864: error: "OrderManager" has no attribute "update_db"
868: error: "OrderManager" has no attribute "update_db"
900: error: Argument 2 for "super" not an instance of argument 1
901: error: "object" has no attribute "queue"
902: error: "object" has no attribute "min_similarity"
906: error: "object" has no attribute "engine"
906: error: "object" has no attribute "order_manager"
907: error: "object" has no attribute "engine"
961: error: Argument 2 for "super" not an instance of argument 1
962: error: "object" has no attribute "queue"
963: error: "object" has no attribute "min_similarity"
967: error: "object" has no attribute "engine"
967: error: "object" has no attribute "order_manager"
968: error: "object" has no attribute "engine"
982: error: "OrderManager" has no attribute "get_interrupt_control"
988: error: "OrderManager" has no attribute "get_interrupt_control"
993: error: "OrderManager" has no attribute "set_interrupt_control"
1017: error: Argument 2 for "super" not an instance of argument 1
1018: error: "object" has no attribute "queue"
1019: error: "object" has no attribute "min_similarity"
1023: error: "object" has no attribute "order_manager"
1024: error: "object" has no attribute "get_next_item"
1025: error: "object" has no attribute "order_manager"
1026: error: "object" has no attribute "order_manager"
1027: error: "object" has no attribute "order_manager"
1029: error: "object" has no attribute "engine"
1029: error: "object" has no attribute "order_manager"
1030: error: "object" has no attribute "engine"
1031: error: "object" has no attribute "order_manager"
1032: error: "object" has no attribute "order_manager"
1033: error: "object" has no attribute "order_manager"
1035: error: "object" has no attribute "engine"
1035: error: "object" has no attribute "order_manager"
1036: error: "object" has no attribute "engine"
1040: error: "object" has no attribute "order_manager"
1043: error: "object" has no attribute "engine"
1044: error: "object" has no attribute "engine"
1047: error: "object" has no attribute "interrupt_task"
1051: error: "object" has no attribute "check_pick_ability"
1052: error: "object" has no attribute "set_order_id"
1054: error: "object" has no attribute "order_manager"
1055: error: "object" has no attribute "engine"
1056: error: "object" has no attribute "engine"
1059: error: "object" has no attribute "order_manager"
1062: error: "object" has no attribute "order_manager"
1063: error: "object" has no attribute "order_manager"
1064: error: "object" has no attribute "engine"
1065: error: "object" has no attribute "engine"
1068: error: "object" has no attribute "order_manager"
1070: error: "object" has no attribute "order_manager"
1071: error: "object" has no attribute "order_manager"
1072: error: "object" has no attribute "engine"
1073: error: "object" has no attribute "engine"
1081: error: "object" has no attribute "set_order_id"
1083: error: "object" has no attribute "order_manager"
1091: error: "object" has no attribute "order_manager"
1101: error: Incompatible types in assignment (expression has type "object", variable has type "str")
1103: error: "OrderManager" has no attribute "get_interrupt_control"
1104: error: "OrderManager" has no attribute "get_interrupt_control"
1107: error: "OrderManager" has no attribute "get_interrupt_control"
1108: error: "OrderManager" has no attribute "set_interrupt_control"
1110: error: "OrderManager" has no attribute "get_interrupt_control"
1111: error: "OrderManager" has no attribute "set_interrupt_control"
1113: error: "OrderManager" has no attribute "get_interrupt_control"
1116: error: "OrderManager" has no attribute "update_db"
1117: error: "OrderManager" has no attribute "get_interrupt_control"
1122: error: "OrderManager" has no attribute "creat_list_order"
1123: error: "OrderManager" has no attribute "update_db"
1167: error: Argument 1 to "check_order_triger" of "OrderManager" has incompatible type "object"; expected "str"</failure></testcase><testcase classname="src.assistant3.processors.base_processor" name="YAPF" time="1.265" /><testcase classname="src.assistant3.processors.bestellung_definition" name="PYLINT" time="0.001"><failure message="F:  1, 0: No module named src/assistant3/processors/bestellung_definition.py (fatal)">F:  1, 0: No module named src/assistant3/processors/bestellung_definition.py (fatal)</failure></testcase><testcase classname="src.assistant3.processors.bestellung_definition.flake-8" name="FLAKE8" time="0.126" /><testcase classname="src.assistant3.processors.bestellung_definition" name="mypy" time="0.001" /><testcase classname="src.assistant3.processors.bestellung_definition" name="YAPF" time="0.050" /><testcase classname="src.assistant3.processors.bestellung_management" name="PYLINT" time="0.002"><failure message="F:  1, 0: No module named src/assistant3/processors/bestellung_management.py (fatal)">F:  1, 0: No module named src/assistant3/processors/bestellung_management.py (fatal)</failure></testcase><testcase classname="src.assistant3.processors.bestellung_management.flake-8" name="FLAKE8" time="2.809" /><testcase classname="src.assistant3.processors.bestellung_management" name="mypy" time="0.001" /><testcase classname="src.assistant3.processors.bestellung_management" name="YAPF" time="0.433" /><testcase classname="src.assistant3.processors.collect_pick" name="PYLINT" time="0.001"><failure message="F:  1, 0: No module named src/assistant3/processors/collect_pick.py (fatal)">F:  1, 0: No module named src/assistant3/processors/collect_pick.py (fatal)</failure></testcase><testcase classname="src.assistant3.processors.collect_pick.flake-8" name="FLAKE8" time="1.372"><failure message="/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/collect_pick.py:19:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/collect_pick.py:39:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/collect_pick.py:60:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/collect_pick.py:80:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/collect_pick.py:116:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/collect_pick.py:139:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/collect_pick.py:165:1: D413 Missing blank line after last section&#10;">/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/collect_pick.py:19:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/collect_pick.py:39:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/collect_pick.py:60:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/collect_pick.py:80:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/collect_pick.py:116:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/collect_pick.py:139:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/collect_pick.py:165:1: D413 Missing blank line after last section
</failure></testcase><testcase classname="src.assistant3.processors.collect_pick" name="mypy" time="0.003"><failure message="27: error: &quot;object&quot; has no attribute &quot;rack_object&quot;&#10;31: error: &quot;object&quot; has no attribute &quot;order_status&quot;&#10;47: error: &quot;object&quot; has no attribute &quot;pick_order_ability&quot;&#10;48: error: &quot;object&quot; has no attribute &quot;rack_object&quot;&#10;51: error: &quot;object&quot; has no attribute &quot;rack_object&quot;&#10;57: error: &quot;object&quot; has no attribute &quot;pick_order_ability&quot;&#10;73: error: &quot;object&quot; has no attribute &quot;check_collected&quot;&#10;75: error: &quot;object&quot; has no attribute &quot;check_picked&quot;&#10;91: error: &quot;object&quot; has no attribute &quot;rack_object&quot;&#10;110: error: &quot;object&quot; has no attribute &quot;rack_object&quot;&#10;124: error: &quot;object&quot; has no attribute &quot;pick_order_ability&quot;&#10;125: error: &quot;object&quot; has no attribute &quot;rack_object&quot;&#10;128: error: &quot;object&quot; has no attribute &quot;db_object&quot;&#10;136: error: &quot;object&quot; has no attribute &quot;pick_order_ability&quot;&#10;138: error: Missing return statement&#10;146: error: &quot;object&quot; has no attribute &quot;rack_object&quot;&#10;152: error: &quot;object&quot; has no attribute &quot;order_status&quot;&#10;155: error: &quot;object&quot; has no attribute &quot;collect_order_with_id&quot;&#10;160: error: &quot;object&quot; has no attribute &quot;rack_object&quot;&#10;162: error: Incompatible return value type (got &quot;int&quot;, expected &quot;Dict[Any, Any]&quot;)&#10;172: error: Incompatible types in assignment (expression has type &quot;int&quot;, variable has type &quot;datetime&quot;)&#10;174: error: &quot;object&quot; has no attribute &quot;rack_object&quot;&#10;180: error: &quot;object&quot; has no attribute &quot;order_status&quot;&#10;181: error: &quot;object&quot; has no attribute &quot;db_object&quot;&#10;184: error: &quot;object&quot; has no attribute &quot;rack_object&quot;&#10;186: error: &quot;object&quot; has no attribute &quot;pick_order_info&quot;&#10;189: error: &quot;object&quot; has no attribute &quot;rack_object&quot;&#10;191: error: Incompatible return value type (got &quot;int&quot;, expected &quot;Dict[Any, Any]&quot;)">27: error: "object" has no attribute "rack_object"
31: error: "object" has no attribute "order_status"
47: error: "object" has no attribute "pick_order_ability"
48: error: "object" has no attribute "rack_object"
51: error: "object" has no attribute "rack_object"
57: error: "object" has no attribute "pick_order_ability"
73: error: "object" has no attribute "check_collected"
75: error: "object" has no attribute "check_picked"
91: error: "object" has no attribute "rack_object"
110: error: "object" has no attribute "rack_object"
124: error: "object" has no attribute "pick_order_ability"
125: error: "object" has no attribute "rack_object"
128: error: "object" has no attribute "db_object"
136: error: "object" has no attribute "pick_order_ability"
138: error: Missing return statement
146: error: "object" has no attribute "rack_object"
152: error: "object" has no attribute "order_status"
155: error: "object" has no attribute "collect_order_with_id"
160: error: "object" has no attribute "rack_object"
162: error: Incompatible return value type (got "int", expected "Dict[Any, Any]")
172: error: Incompatible types in assignment (expression has type "int", variable has type "datetime")
174: error: "object" has no attribute "rack_object"
180: error: "object" has no attribute "order_status"
181: error: "object" has no attribute "db_object"
184: error: "object" has no attribute "rack_object"
186: error: "object" has no attribute "pick_order_info"
189: error: "object" has no attribute "rack_object"
191: error: Incompatible return value type (got "int", expected "Dict[Any, Any]")</failure></testcase><testcase classname="src.assistant3.processors.collect_pick" name="YAPF" time="0.428" /><testcase classname="src.assistant3.processors.make_db" name="PYLINT" time="0.002"><failure message="F:  1, 0: No module named src/assistant3/processors/make_db.py (fatal)">F:  1, 0: No module named src/assistant3/processors/make_db.py (fatal)</failure></testcase><testcase classname="src.assistant3.processors.make_db.flake-8" name="FLAKE8" time="1.271" /><testcase classname="src.assistant3.processors.make_db" name="mypy" time="0.001"><failure message="104: error: Incompatible return value type (got &quot;str&quot;, expected &quot;Tuple[Any, ...]&quot;)">104: error: Incompatible return value type (got "str", expected "Tuple[Any, ...]")</failure></testcase><testcase classname="src.assistant3.processors.make_db" name="YAPF" time="0.207" /><testcase classname="src.assistant3.processors.make_racks" name="PYLINT" time="0.001"><failure message="F:  1, 0: No module named src/assistant3/processors/make_racks.py (fatal)">F:  1, 0: No module named src/assistant3/processors/make_racks.py (fatal)</failure></testcase><testcase classname="src.assistant3.processors.make_racks.flake-8" name="FLAKE8" time="0.762"><failure message="/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:17:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:44:13: SIM115 Use context handler for opening files&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:78:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:98:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:123:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:134:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:147:1: D413 Missing blank line after last section&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:154:9: SIM115 Use context handler for opening files&#10;/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:158:1: D413 Missing blank line after last section&#10;">/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:17:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:44:13: SIM115 Use context handler for opening files
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:78:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:98:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:123:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:134:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:147:1: D413 Missing blank line after last section
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:154:9: SIM115 Use context handler for opening files
/home/TEST.PYvenv/manager_order/b/src/assistant3/processors/make_racks.py:158:1: D413 Missing blank line after last section
</failure></testcase><testcase classname="src.assistant3.processors.make_racks" name="mypy" time="0.001"><failure message="22: error: &quot;object&quot; has no attribute &quot;db_object&quot;&#10;23: error: &quot;object&quot; has no attribute &quot;add_json_order&quot;&#10;28: error: &quot;object&quot; has no attribute &quot;generate_json_order&quot;&#10;30: error: &quot;object&quot; has no attribute &quot;open_new_file&quot;&#10;37: error: &quot;object&quot; has no attribute &quot;generate_file_name&quot;&#10;42: error: &quot;object&quot; has no attribute &quot;db_object&quot;&#10;43: error: &quot;object&quot; has no attribute &quot;generate_file_name&quot;&#10;47: error: &quot;object&quot; has no attribute &quot;write_json_file&quot;&#10;52: error: &quot;object&quot; has no attribute &quot;read_jason_file&quot;&#10;53: error: &quot;object&quot; has no attribute &quot;db_object&quot;&#10;61: error: No overload variant of &quot;dict&quot; matches argument types &quot;int&quot;, &quot;int&quot;&#10;61: note: Possible overload variants:&#10;61: note:     def [_KT, _VT] dict(self) -&gt; Dict[_KT, _VT]&#10;61: note:     def [_KT, _VT] dict(self, **kwargs: _VT) -&gt; Dict[str, _VT]&#10;61: note:     def [_KT, _VT] dict(self, SupportsKeysAndGetItem[_KT, _VT], **kwargs: _VT) -&gt; Dict[_KT, _VT]&#10;61: note:     def [_KT, _VT] dict(self, Iterable[Tuple[_KT, _VT]], **kwargs: _VT) -&gt; Dict[_KT, _VT]&#10;61: note:     def [_KT, _VT] dict(self, Iterable[List[str]]) -&gt; Dict[str, str]&#10;64: error: &quot;object&quot; has no attribute &quot;open_file&quot;&#10;72: error: &quot;object&quot; has no attribute &quot;open_file&quot;&#10;75: error: &quot;object&quot; has no attribute &quot;read_jason_file&quot;&#10;86: error: &quot;object&quot; has no attribute &quot;find_order_place&quot;&#10;90: error: &quot;object&quot; has no attribute &quot;read_jason_file&quot;&#10;92: error: &quot;object&quot; has no attribute &quot;open_file&quot;&#10;108: error: &quot;object&quot; has no attribute &quot;read_jason_file&quot;&#10;117: error: &quot;object&quot; has no attribute &quot;read_jason_file&quot;&#10;142: error: &quot;object&quot; has no attribute &quot;generate_file_name&quot;&#10;146: error: &quot;list&quot; expects 1 type argument, but 2 given&#10;152: error: &quot;object&quot; has no attribute &quot;generate_file_name&quot;&#10;153: error: &quot;object&quot; has no attribute &quot;generate_file_name&quot;&#10;155: error: &quot;object&quot; has no attribute &quot;write_json_file&quot;&#10;157: error: &quot;list&quot; expects 1 type argument, but 2 given&#10;163: error: &quot;object&quot; has no attribute &quot;generate_file_name&quot;">22: error: "object" has no attribute "db_object"
23: error: "object" has no attribute "add_json_order"
28: error: "object" has no attribute "generate_json_order"
30: error: "object" has no attribute "open_new_file"
37: error: "object" has no attribute "generate_file_name"
42: error: "object" has no attribute "db_object"
43: error: "object" has no attribute "generate_file_name"
47: error: "object" has no attribute "write_json_file"
52: error: "object" has no attribute "read_jason_file"
53: error: "object" has no attribute "db_object"
61: error: No overload variant of "dict" matches argument types "int", "int"
61: note: Possible overload variants:
61: note:     def [_KT, _VT] dict(self) -&gt; Dict[_KT, _VT]
61: note:     def [_KT, _VT] dict(self, **kwargs: _VT) -&gt; Dict[str, _VT]
61: note:     def [_KT, _VT] dict(self, SupportsKeysAndGetItem[_KT, _VT], **kwargs: _VT) -&gt; Dict[_KT, _VT]
61: note:     def [_KT, _VT] dict(self, Iterable[Tuple[_KT, _VT]], **kwargs: _VT) -&gt; Dict[_KT, _VT]
61: note:     def [_KT, _VT] dict(self, Iterable[List[str]]) -&gt; Dict[str, str]
64: error: "object" has no attribute "open_file"
72: error: "object" has no attribute "open_file"
75: error: "object" has no attribute "read_jason_file"
86: error: "object" has no attribute "find_order_place"
90: error: "object" has no attribute "read_jason_file"
92: error: "object" has no attribute "open_file"
108: error: "object" has no attribute "read_jason_file"
117: error: "object" has no attribute "read_jason_file"
142: error: "object" has no attribute "generate_file_name"
146: error: "list" expects 1 type argument, but 2 given
152: error: "object" has no attribute "generate_file_name"
153: error: "object" has no attribute "generate_file_name"
155: error: "object" has no attribute "write_json_file"
157: error: "list" expects 1 type argument, but 2 given
163: error: "object" has no attribute "generate_file_name"</failure></testcase><testcase classname="src.assistant3.processors.make_racks" name="YAPF" time="0.190" /><testcase classname="src.assistant3.processors.manager_tools" name="PYLINT" time="0.001"><failure message="F:  1, 0: No module named src/assistant3/processors/manager_tools.py (fatal)">F:  1, 0: No module named src/assistant3/processors/manager_tools.py (fatal)</failure></testcase><testcase classname="src.assistant3.processors.manager_tools.flake-8" name="FLAKE8" time="0.666" /><testcase classname="src.assistant3.processors.manager_tools" name="mypy" time="0.003" /><testcase classname="src.assistant3.processors.manager_tools" name="YAPF" time="0.311" /><testcase classname="src.assistant3.processors.monthly_plan_for_testing" name="PYLINT" time="0.002"><failure message="F:  1, 0: No module named src/assistant3/processors/monthly_plan_for_testing.py (fatal)">F:  1, 0: No module named src/assistant3/processors/monthly_plan_for_testing.py (fatal)</failure></testcase><testcase classname="src.assistant3.processors.monthly_plan_for_testing.flake-8" name="FLAKE8" time="2.532" /><testcase classname="src.assistant3.processors.monthly_plan_for_testing" name="mypy" time="0.001"><failure message="8: error: Cannot find implementation or library stub for module named &quot;xlsxwriter&quot;">8: error: Cannot find implementation or library stub for module named "xlsxwriter"</failure></testcase><testcase classname="src.assistant3.processors.monthly_plan_for_testing" name="YAPF" time="0.865" /><testcase classname="src.assistant3.processors.nlp_keys" name="PYLINT" time="0.001"><failure message="F:  1, 0: No module named src/assistant3/processors/nlp_keys.py (fatal)">F:  1, 0: No module named src/assistant3/processors/nlp_keys.py (fatal)</failure></testcase><testcase classname="src.assistant3.processors.nlp_keys.flake-8" name="FLAKE8" time="0.590" /><testcase classname="src.assistant3.processors.nlp_keys" name="mypy" time="0.003"><failure message="23: error: List comprehension has incompatible type List[int]; expected List[str]&#10;29: error: List comprehension has incompatible type List[int]; expected List[str]">23: error: List comprehension has incompatible type List[int]; expected List[str]
29: error: List comprehension has incompatible type List[int]; expected List[str]</failure></testcase><testcase classname="src.assistant3.processors.nlp_keys" name="YAPF" time="0.278" /></testsuite></testsuites>